# Generated by Django 3.2.6 on 2023-11-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kumia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, default='media/post.jpg', null=True, upload_to='post/')),
                ('body', models.TextField(blank=True, max_length=300, null=True)),
                ('post_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='slide',
            name='image',
            field=models.ImageField(blank=True, default='media/slide.jpg', null=True, upload_to='slides/'),
        ),
    ]
